export enum EAppPaths {
    MAIN = "/",
    MAIN_PAGES = "/pages/:pageNumber",
    ABOUT = "/about",
    CONTACT = "/contact",
    LOGIN = "/login",
    PROFILE = "/profile",
    ADMIN = "/admin",
    EDIT_ABOUT_ME = "/edit-about-me",
    EDIT_CONTACTS = "/edit-contacts",
    LOGOUT = "/logout",
    ERROR = "/error",
    MESSAGE_ADMIN = "/messageAdmin",
    CREATE_ARTICLE = "/create-article",
    ARTICLE = "/article/:articleId",
    MY_ARTICLES = "/my-articles",
    EDIT_ARTICLE = "/edit-article/:articleId",
    USER = "/user/:userId",
}
