const domen = "http://localhost:8080/";

export const ApiRoutes = {
    ADD_USER: `${domen}user/add`,
    CHECK_LOGIN_EXIST: `${domen}login/check`,
    CHECK_EMAIL_EXIST: `${domen}email/check`,
    CONFIRM_CODE: `${domen}code/confirm`,
    LOGIN: `${domen}login`,
    GET_USERS: `${domen}admin/users`,
    RESEND_CODE: `${domen}code/resend`,
    GET_USER: `${domen}user/get`,
    GET_USER_BY_ID: `${domen}user/getById`,
    BLOCK_USER: `${domen}user/block`,
    UNBLOCK_USER: `${domen}user/unblock`,
    CHANGE_ROLE: `${domen}user/changeRole`,
    SEND_EMAIL: `${domen}user/send-email`,
    GET_ROLE: `${domen}user/role`,
    CHANGE_LOGIN: `${domen}login/change`,
    CHANGE_EMAIL: `${domen}email/change`,
    CHANGE_PASSWORD: `${domen}password/change`,
    FORGOT_PASSWORD: `${domen}password/forgot`,
    DELETE_USER: `${domen}user/delete`,
    UPLOAD_AVATAR: `${domen}avatar/upload`,
    DELETE_AVATAR: `${domen}avatar/delete`,
    UPLOAD_ARTICLE: `${domen}article/upload`,
    EDIT_ARTICLE: `${domen}article/edit`,
    GET_ARTICLES: `${domen}article/page/:pageNumber`,
    DELETE_ARTICLE: `${domen}article/delete`,
    MY_ARTICLES: `${domen}article/my`,
    GET_ARTICLE_BY_ID: `${domen}article/:articleId`,
    GET_COMMENTS: `${domen}comments/:articleId`,
    ADD_COMMENT: `${domen}comments/add`,
    DELETE_COMMENT: `${domen}comments/delete`,
    EDIT_ABOUT_ME: `${domen}admin/about-me/edit`,
    GET_ABOUT_ME: `${domen}admin/about-me/get`,
    GET_CONTACTS: `${domen}admin/contacts/get`,
    EDIT_CONTACTS: `${domen}admin/contacts/edit`,
    GET_USER_PROFILE: `${domen}user/profile/:userId`,
};
